apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: donor-init
          configMap:
            name: init
        - name: donor-config
          configMap:
            name: config
        - name: init
          emptyDir: {}
        - name: config
          emptyDir: {}
      initContainers:
        - name: init
          image: alpine
          volumeMounts:
            - name: donor-init
              mountPath: /from/init
            - name: donor-config
              mountPath: /from/config
            - name: init
              mountPath: /to/init
            - name: config
              mountPath: /to/config
          command:
            - sh
            - -c
            - cp -r /from/init/. /to/init ; cp -r /from/config/. /to/config
      containers:
        - name: postgres
          image: postgres:12-alpine
          args:
            - --config_file=/var/lib/postgresql/config/postgresql.conf
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: init
              mountPath: /docker-entrypoint-initdb.d
            - name: config
              mountPath: /var/lib/postgresql/config
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: postgres
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi